azure_storage_connection_string: "DefaultEndpointsProtocol=https;AccountName=oasisaigenerated;AccountKey=01jvAt1GT9wNNeeEwbS71Nz8CPj6NNa6nR/4KEQ9ONGYgBQfekwCKhvc3tjgZTekl2IpDMjClFiz+AStUKuzyQ==;EndpointSuffix=core.windows.net"
audio_cotainer: "generatedaudiolug"
source_folder: "/luganda"