name: lugtts-model-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python == 3.9  
  - pip 
  - pip:
    - azureml-defaults==1.47.0
    - pyyaml
    - azure-storage-blob
    - inference-schema[numpy-support]==1.5
    - speechbrain
    - torch
    - torchaudio
    - scipy == 1.7.1  # Specify the required version of scipy
    - numpy == 1.21.2  # Specify the required version of numpy
    - setuptools  # Include setuptools explicitly